// Auto-generated by OpenLane
module systolic_sorter(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input clk,
  input rst,
  input load,
  input[255:0] in_data_flat,
  output[255:0] out_data_flat
);
endmodule
